from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('work/codingDojo/', views.cd),
    path('work/sirch/', views.sirch),
    path('work/beedev/', views.bd),
    path('learning/lambda/', views.bloomTech),
    path('learning/microsoft/', views.microsoft),
    path('learning/scotch/', views.scotch),
    path('learning/schools/', views.schools),
    path('coding/volunteer/', views.volunteer),
    path('coding/hackathons/', views.hack),
    path('coding/personal/', views.websites),
    path('logReg/', views.logReg),
    path('login/', views.login),
    path('register/', views.register),
    path('dashboard/', views.adminDash),
    path('logout/', views.logout),
    path('theAdmin/createPage/', views.createPage),
    path('theAdmin/createType/', views.createType),
    path('theAdmin/createTopic/', views.createTopic),
    path('theAdmin/createLink/', views.createLink),
    path('theAdmin/page/<int:page_id>/edit/', views.editPage),
    path('theAdmin/type/<int:type_id>/edit/', views.editType),
    path('theAdmin/topic/<int:topic_id>/edit/', views.editTopic),
    path('theAdmin/links/<int:link_id>/edit/', views.editLink),
    path('theAdmin/page/<int:page_id>/update/', views.updatePage),
    path('theAdmin/type/<int:type_id>/update/', views.updateType),
    path('theAdmin/topic/<int:topic_id>/update/', views.updateTopic),
    path('theAdmin/links/<int:link_id>/update/', views.updateLink),
    path('theAdmin/page/<int:page_id>/delete/', views.deletePage),
    path('theAdmin/type/<int:type_id>/delete/', views.deleteType),
    path('theAdmin/topic/<int:topic_id>/delete/', views.deleteTopic),
    path('theAdmin/links/<int:link_id>/delete/', views.deleteLink),
]